name:                legalruleml-thinger
version:             0.1.0.0
github:              "flaviusb/legalruleml-thinger"
license:             GPL-3
author:              "Justin (:flaviusb) Marsh"
maintainer:          "justin.marsh@flaviusb.net"
copyright:           "Justin (:flaviusb) Marsh 2018"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            application

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/flaviusb/legalruleml-thinger#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  legalruleml-thinger-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - legalruleml-thinger

tests:
  legalruleml-thinger-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - legalruleml-thinger
